language: android
android:
    components:
        - platform-tools
        - tools

        - build-tools-29.0.2

        - android-23
        
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

before_script:
        - chmod +x gradlew

script: "app/build/outputs/apk/debug/app-debug.apk"

deploy:
    provider: releases
    api_key:
        secure: 1cfefe2b07c1bbd963316cb5a54a869bbe75482a
    file: app/src/app-release.apk
    skip_cleanup: true
    on:
        repo: https://github.com/GewoonGianni/Minimal-Todo
        tags: true